### ISSUE TITLE
Wrong usage of <main> element

### ISSUE THREAD

**Issue by sebastianbaumann** [mfouquet/workmanship#11]
There must not be more than one main element in a document. You can have a look at [ w3schools](http://www.w3schools.com/tags/tag_main.asp) for more information regarding the correct usage.

By the way… there are several more errors like closing h5 tags with h3 for example. Maybe you should check the markup of your page against some html validators.

**Comment by mfouquet** [comment]
Thanks for the heads up - appreciate it. Merged in a couple branches that should take care of the errors you mentioned. Also ran it through a validator per your suggestion. Thanks again.
