### ISSUE TITLE
Border & box model

### ISSUE THREAD

**Issue by pieter-biesemans** [mfouquet/workmanship#14]
In the CSS part you write:

> Adhere to this property order:
> Positioning (position, z-index...)
> Box Model (display, margin...)
> Typographic (font, color...)
> Visual (border, opacity...)

One could argue _border_ belongs under Box Model, since border widths add to height and width of the box...

**Comment by revoltpuppy** [comment]
I agree with this one.

**Comment by mfouquet** [comment]
Very true - I included it with visual since a majority of properties around border are visual in nature. For the sake of clarity though, I'll fix this since border absolutely belongs under Box Model.

**Comment by pieter-biesemans** [comment]
Thanks. It's no biggie, but it was nagging me ;) Thanks for fixing!
